### ISSUE TITLE
A way to use a pointer as key? without compiler warnings

### ISSUE THREAD

**Issue by NickWilde263** [DavidLeeds/hashmap#11]

**Comment by DavidLeeds** [comment]
```c
/* Arbitrary key type */
struct key { ... };
struct value { ... }

HASHMAP(struct key, struct value) map;

/* Use the map, passing in `struct key *` as the key, and `struct value *` as the value */
```

**Comment by NickWilde263** [comment]
> ```c
> /* Arbitrary key type */
> struct key { ... };
> struct value { ... }
> 
> HASHMAP(struct key, struct value) map;
> 
> /* Use the map, passing in `struct key *` as the key, and `struct value *` as the value */
> ```

wait so i dont pass it like `struct key*`
ah, that where my mistake is
