### ISSUE TITLE
Suggestion: Consider add this library to clib https://github.com/clibs/clib?

### ISSUE THREAD

**Issue by NickWilde263** [DavidLeeds/hashmap#16]
I have using this ~6 months now and quality is great so im asking about considering adding it to clib packages list as clib still dont have any type templated hashmap implementation yet

**Comment by DavidLeeds** [comment]
Hi @NickWilde263,

I haven't used clib before, but I'd be happy to add a `package.json` so this project can be compatible.

**Comment by NickWilde263** [comment]
done https://github.com/clibs/clib/wiki/Packages its in the clib packages registry

**Comment by DavidLeeds** [comment]
Thanks!

**Comment by NickWilde263** [comment]
you're welcome :)
![fundyHappy](https://user-images.githubusercontent.com/67861857/158916232-aabacc77-f707-4140-8a98-466507b54292.png)
