### ISSUE TITLE
How to build in nodebug mode

### ISSUE THREAD

**Issue by CanYouGiveMeAName** [DavidLeeds/hashmap#8]
I need to run this lib in sgx. But sgx do not support __assert_fail. So I need to make in no debug mode.

Please help. Thanks

**Comment by DavidLeeds** [comment]
You should be able to compile out assertions by defining `NDEBUG` at compile time. If you're using CMake, you could do something like `target_compile_definitions(hashmap PRIVATE NDEBUG)`.
